[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
dimensions = { columns = 120, lines = 35}

[font]
normal.family = "CommitMonoNerdFont"
italic.family = "CommitMonoNerdFont"
bold.family = "CommitMonoNerdFont"
bold_italic.family = "CommitMonoNerdFont"
normal.style = "Regular"
bold.style = "Bold"
bold_italic.style = "BoldItalic"

[colors]
primary.foreground = "#EEEEEE"
primary.background = "#282828"

[colors.search]
matches.foreground = "#4C4C4C"
matches.background = "#7c5c20"

focused_match.foreground = "#4C4C4C"
focused_match.background = "#dbb671"

[colors.hints]
start.foreground = "#282828"
start.background = "#358CA7"

end.foreground = "#282828"
end.background = "#de5d68"

[colors.footer_bar]
foreground = "#4C4C4C"
background = "#51a8b3"

[colors.normal]
black = "#282828"
red = "#FF064D"
green = "#C6D243"
blue = "#A8DFF1"
yellow = "#FFC020"
cyan = "#358CA7"
magenta = "#D8B980"
white = "#EEEEEE"

[colors.bright]
black = "#4C4C4C"
red = "#FA104B"
green = "#B8C33E"
blue = "#A4DAEB"
yellow = "#FFC020"
cyan = "#45B6D9"
magenta = "#D8B980"
white = "#EEEEEE"

[cursor.style]
blinking = "On"

[terminal]
