[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
dimensions = { columns = 120, lines = 30}

[colors]
primary.foreground = "#a7aab0"
primary.background = "#37383d"

[colors.search]
matches.foreground = "#37383d"
matches.background = "#7c5c20"

focused_match.foreground = "#37383d"
focused_match.background = "#dbb671"

[colors.hints]
start.foreground = "#37383d"
start.background = "#51a8b3"

end.foreground = "#37383d"
end.background = "#de5d68"

[colors.footer_bar]
foreground = "#37383d"
background = "#51a8b3"

[colors.normal]
black = "#101012"
red = "#de5d68"
green = "#8fb573"
blue = "#57a5e5"
yellow = "#dbb671"
cyan = "#51a8b3"
magenta = "#bb70d2"
white = "#D4C9C9"

[colors.bright]
black = "#101012"
red = "#de5d68"
green = "#8fb573"
blue = "#57a5e5"
yellow = "#dbb671"
cyan = "#51a8b3"
magenta = "#bb70d2"
white = "#D4C9C9"

[cursor.style]
blinking = "On"
