[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
dimensions = { columns = 120, lines = 40}
opacity = 0.9

[font]
normal.family = "CommitMonoNerdFont"
italic.family = "CommitMonoNerdFont"
bold.family = "CommitMonoNerdFont"
bold_italic.family = "CommitMonoNerdFont"
normal.style = "Regular"
bold.style = "Bold"
bold_italic.style = "BoldItalic"

[colors]
primary.foreground = "#EAE7E5"
primary.background = "#0D0D0D"

[colors.search]
matches.foreground = "#0D0D0D"
matches.background = "#D6A83A"

focused_match.foreground = "#FFFFFF"
focused_match.background = "#D12B18"

[colors.hints]
start.foreground = "#0D0D0D"
start.background = "#35A6B5"

end.foreground = "#FFFFFF"
end.background = "#D12B18"

[colors.footer_bar]
foreground = "#EAE7E5"
background = "#222222"

[colors.normal]
black   = "#161616"
red     = "#D12B18"
green   = "#789B4A"
yellow  = "#D6A83A"
blue    = "#4D83B3"
magenta = "#A65B82"
cyan    = "#187F8F"
white   = "#EAE7E5"

[colors.bright]
black   = "#363636"
red     = "#E95745"
green   = "#9ABF69"
yellow  = "#E9C15B"
blue    = "#70A4D2"
magenta = "#C77AA0"
cyan    = "#35A6B5"
white   = "#FFFFFF"

[cursor.style]
blinking = "On"

[terminal]
